### ISSUE TITLE
Maybe renaming the project to prettier-postgresql?

### ISSUE THREAD

**Issue by lipis** [benjie/prettier-plugin-pg-sql#3]
or `prettier-postgre-sql`?

(to much the rest of the languages)

**Comment by benjie** [comment]
Prettier plugins need to start either `prettier-plugin-` or `@prettier/plugin-`; but we could potentially rename it to `prettier-plugin-postgresql` or just `prettier-plugin-pg`. I'm not yet sure whether PLPGSQL support will be provided by this plugin or by another one - I've not explored the PLPGSQL AST yet - it may or may not use the same parser as SQL.

**Comment by benjie** [comment]
Renamed to `prettier-plugin-pg` after the `pg` module.

**Comment by lipis** [comment]
https://github.com/prettier/prettier/pull/3758/files no plugins were released yet officially, but so far that was the naming convention..

**Comment by benjie** [comment]
I got the naming from the plugin docs:

>  Prettier plugin package names must start with `@prettier/plugin-` or `prettier-plugin-` to be registered.
> -- https://prettier.io/docs/en/plugins.html

I think you're referring to the repository names rather than the package names.

**Comment by lipis** [comment]
Right.. I was referring to the project name and so far the first option is being used.. dunno :|

**Comment by benjie** [comment]
Personally I'm not a fan of the repo name and the package name not matching up - I find it to cause confusion. I'm open to renaming it to match the others though, or even for it to move under the `@prettier` organisation.

**Comment by azz** [comment]
I might be renaming the official plugins prior to their release, the conventional loading was added after they were initially named.

Package: `@prettier/plugin-python`, Repo: `prettier/plugin-python`

**Comment by benjie** [comment]
👍  I think that'd be a good move. Does that mean I should stick with the current name `prettier-plugin-pg`?

**Comment by azz** [comment]
Up to you. Is the official name of the language "PL/pgSQL"?

**Comment by benjie** [comment]
Short answer: no, it's simply "SQL". 

Long answer: `PL/pgSQL` is one of the procedural languages that can be used within PostgreSQL database functions (others include `PL/v8` and `PL/python`), but the primary language (outside of functions) is just SQL. However, most databases implement SQL slightly differently, and support different features, so it's PostgreSQL-flavoured SQL - that's why I originally called it `prettier-plugin-pg-sql`. I think `prettier-plugin-pg` is clear enough though, and shorter means less likelihood of typos 😉
